language: python
branches:
  only:
  - master
sudo: "required"
services:
  - docker
env:
  matrix:
    - ACTION=pylint
      OS=fedora
      OS_VERSION=28
      PYTHON_VERSION=2
    - ACTION=pylint
      OS=fedora
      OS_VERSION=28
      PYTHON_VERSION=3
    - OS=centos
      OS_VERSION=7
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=27
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=27
      PYTHON_VERSION=3
    - OS=fedora
      OS_VERSION=28
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=28
      PYTHON_VERSION=3
script:
 - pip install coveralls
 - ./test.sh
after_success: coveralls
notifications:
  email: false
